name: Release
on:
  schedule:
    - cron: '0 12 * * 1,4' # 12:00 UTC Monday and Thursday
  # manual trigger
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
      changelog: ${{ steps.github-tag-action.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump and tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          default_bump: patch

  release:
    needs: tag
    if: ${{ needs.tag.outputs.new_tag != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn postinstall
      - run: yarn build
      - run: yarn export

      - name: Pin to IPFS (Filebase)
        id: filebase
        uses: aquiladev/ipfs-action@master
        with:
          path: './out'
          service: filebase
          pinName: 'ipfs-action'
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

      - name: Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          release_name: Aelin ${{ needs.tag.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - CID v1: `${{ steps.filebase.outputs.hash }}`

            Public IPFS Subdomain Gateways:
            - Cloudflare: https://${{ steps.filebase.outputs.hash }}.ipfs.cf-ipfs.com/
            - Web3 Storage: https://${{ steps.filebase.outputs.hash }}.ipfs.w3s.link/
            - dWeb Link: https://${{ steps.filebase.outputs.hash }}.ipfs.dweb.link/

            ${{ needs.tag.outputs.changelog }}
